name: Python CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install the coverage package
      - name: Install dependencies
        run: pip install coverage

      # Run tests with coverage and enforce minimum coverage of 80%
      - name: Run tests and generate coverage report
        run: |
          coverage run -m unittest discover
          coverage report --fail-under=80