name: Python CI

# Triggers the workflow on push or pull request events for the main or master branch
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Sets up the Python version
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Runs the built-in unittest discovery
      - name: Run tests
        run: python -m unittest discover